---
name: Build and Push Config Service docker image to GCP

on:
  push: 
    branches: ["main"]
  
jobs:
  build-push-gcp:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'gcp build')
    env:
      IMAGE_NAME: config-server
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ env.PROJECT_ID }}
        version: '>= 416.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v patch
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        mvn compile com.google.cloud.tools:jib-maven-plugin:3.3.2:build \
        -Djib.from.image=eclipse-temurin \
        -Djib.to.image=us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

