---
name: Build and Push Config Service docker image to GCP

on:
  push: 
    branches: ["main"]
  
jobs:
  build-push-gcp:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: config-server
      PROJECT_ID: ${{secrets.PROJECT_ID}}
      SECRET_ID: ${{secrets.SERVICE_ACCOUNT_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ env.SECRET_ID }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v patch
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.1:build \
        -Djib.from.image=eclipse-temurin \
        -Djib.to.image=us-central1-docker.pkg.dev/${{env.PROJECT_ID}}/config-server-images/$IMAGE_NAME
        -Djib.to.tags=latest,${{ GIT_TAG }}

    
